"""Codegen for the DesignJob module of a generated design package.

Uses string.Template (not f-strings) because the generated source is full of
braces. The generated module is self-contained: it embeds the Tier-0
reference list and the DeviceType fingerprint algorithm so the design git
repo has no import-time dependency on this library.

The fingerprint snippet below MUST stay in lockstep with
jobs/capture/component_diff.py::fingerprint_device_type.
"""

from __future__ import annotations

import json
from string import Template

from ..escape import Placeholder
from ..params import ParamMap
from ..rewrite import apply_name_patterns
from ..spec import SiteSpec

_MODULE_TEMPLATE = Template(
    '''"""Generated by nautobot-design-template-factory — DO NOT EDIT.

Template: ${template_id} (source site ${source_site_code})
Regenerate with: dtf render <spec.json> <param-map.yaml>
"""

import hashlib
import ipaddress
import json

from nautobot.apps.jobs import IPNetworkVar, ObjectVar, StringVar
from nautobot.dcim.models import Location

from nautobot_design_builder.context import Context
from nautobot_design_builder.design_job import DesignJob
${extension_import}

# Tier-0 shared objects this design references and must never create/mutate.
# Verified-or-fail before the engine runs (see validators below).
REFERENCES = json.loads(
    r"""
${references_json}
"""
)

SUPERNET_SEEDS = ${supernet_seeds}
EXPECTED_PARENT_LOCATION_TYPE = ${parent_location_type}
# Site-code-derived names this design will create; checked for pre-existing
# collisions at deploy time ('{site_code}' is substituted with the input).
CREATED_NAME_TEMPLATES = ${created_name_templates}
PROVISIONED_FROM_FIELD = "provisioned_from"


def _fingerprint_device_type(device_type):
    """Must match design_template_factory capture fingerprinting exactly."""
    template_related_names = (
        "console_port_templates",
        "console_server_port_templates",
        "power_port_templates",
        "power_outlet_templates",
        "interface_templates",
        "rear_port_templates",
        "front_port_templates",
        "device_bay_templates",
        "module_bay_templates",
    )
    parts = []
    for related in template_related_names:
        manager = getattr(device_type, related, None)
        if manager is None:
            continue
        for template in manager.all():
            attrs = [
                related,
                template.name,
                str(getattr(template, "type", "")),
                str(getattr(template, "label", "") or ""),
                str(getattr(template, "description", "") or ""),
                str(getattr(template, "mgmt_only", "")),
                str(getattr(template, "positions", "")),
                str(getattr(template, "rear_port_position", "")),
                getattr(getattr(template, "rear_port_template", None), "name", ""),
            ]
            parts.append(":".join(attrs))
    return hashlib.sha256("|".join(sorted(parts)).encode("utf-8")).hexdigest()


class ${class_name}Context(Context):
    """Deploy-time inputs + pre-flight validation.

    Design Builder wires validate_* methods into both the job form's clean()
    and the pre-implementation check, so every failure below surfaces before
    any object is written (the engine itself has no pre-flight phase, and its
    mid-run errors are known to surface poorly — issues #232/#286).
    """

    def _fail(self, message):
        from nautobot_design_builder.errors import DesignValidationError

        raise DesignValidationError(message)

    def validate_references(self):
        from nautobot.dcim.models import DeviceType, LocationType, Manufacturer, Platform
        from nautobot.extras.models import CustomField, Role, Status, Tag
        from nautobot.ipam.models import Namespace
        from nautobot.tenancy.models import Tenant

        lookups = {
            "statuses": (Status, "name"),
            "roles": (Role, "name"),
            "tags": (Tag, "name"),
            "manufacturers": (Manufacturer, "name"),
            "platforms": (Platform, "name"),
            "tenants": (Tenant, "name"),
            "namespaces": (Namespace, "name"),
            "location_types": (LocationType, "name"),
        }
        for family, (model, field) in lookups.items():
            for ref in REFERENCES.get(family, []):
                obj = model.objects.filter(**{field: ref[field]}).first()
                if obj is None:
                    self._fail(
                        "%s %r referenced by this design does not exist"
                        % (model.__name__, ref[field])
                    )
                # Content-type gating: the status/role must be enabled for
                # every model this design uses it on.
                for label in ref.get("content_types", []):
                    app_label, model_name = label.split(".")
                    if not obj.content_types.filter(
                        app_label=app_label, model=model_name
                    ).exists():
                        self._fail(
                            "%s %r is not enabled for content type %s"
                            % (model.__name__, ref[field], label)
                        )
        for ref in REFERENCES.get("device_types", []):
            device_type = DeviceType.objects.filter(
                model=ref["model"], manufacturer__name=ref["manufacturer"]
            ).first()
            if device_type is None:
                self._fail(
                    "DeviceType %s/%s does not exist"
                    % (ref["manufacturer"], ref["model"])
                )
            fingerprint = _fingerprint_device_type(device_type)
            if fingerprint != ref["template_fingerprint"]:
                self._fail(
                    "DeviceType %s/%s component templates changed since this "
                    "template was captured (fingerprint mismatch) — re-capture "
                    "the golden site" % (ref["manufacturer"], ref["model"])
                )
        custom_field_names = [
            ref["key"] for ref in REFERENCES.get("custom_fields", [])
        ] + [PROVISIONED_FROM_FIELD]
        for key in custom_field_names:
            if not CustomField.objects.filter(key=key).exists():
                self._fail(
                    "Custom field %r must exist before deploying (see package "
                    "README for setup)" % key
                )

    def validate_parent_location(self):
        parent = self.parent_location
        if EXPECTED_PARENT_LOCATION_TYPE and (
            parent.location_type.name != EXPECTED_PARENT_LOCATION_TYPE
        ):
            self._fail(
                "Parent location %s has type %s; this template expects %s"
                % (parent, parent.location_type.name, EXPECTED_PARENT_LOCATION_TYPE)
            )
        if Location.objects.filter(parent=parent, name=self.site_name).exists():
            self._fail(
                "A location named %r already exists under %s"
                % (self.site_name, parent)
            )

    def validate_no_name_collisions(self):
        """Site-coded names must not already exist anywhere (the identifier
        policy's global-uniqueness guarantee — a collision here means
        create_or_update would mutate a foreign object)."""
        from nautobot.dcim.models import Device, Rack, RackGroup
        from nautobot.ipam.models import VLANGroup

        models = {"devices": Device, "racks": Rack, "rack_groups": RackGroup}
        for family, model in models.items():
            for template_name in CREATED_NAME_TEMPLATES.get(family, []):
                name = template_name.format(site_code=self.site_code)
                if model.objects.filter(name=name).exists():
                    self._fail(
                        "%s named %r already exists — deploying would collide "
                        "(wrong site_code, or site already deployed?)"
                        % (model.__name__, name)
                    )
        for template_name in CREATED_NAME_TEMPLATES.get("vlan_groups", []):
            name = template_name.format(site_code=self.site_code)
            if VLANGroup.objects.filter(name=name).exists():
                self._fail("VLANGroup %r already exists" % name)

    def validate_supernets(self):
        from nautobot.ipam.models import Prefix

        for seed, source in SUPERNET_SEEDS.items():
            value = getattr(self, seed)
            source_net = ipaddress.ip_network(source)
            try:
                seed_net = ipaddress.ip_network(str(value))
            except ValueError:
                self._fail("%s is not a valid network for %s" % (value, seed))
                return
            if seed_net.version != source_net.version:
                self._fail(
                    "%s must be IPv%d (replaces %s)"
                    % (seed, source_net.version, source)
                )
            if seed_net.prefixlen > source_net.prefixlen:
                self._fail(
                    "%s (%s) is smaller than the source supernet %s it replaces"
                    % (seed, seed_net, source)
                )
            # Overlap scan: the rebased prefixes land inside seed_net, so any
            # existing prefix overlapping it is a collision risk. Python-side
            # comparison avoids relying on version-specific ORM net filters.
            namespaces = [ref["name"] for ref in REFERENCES.get("namespaces", [])]
            for network, prefix_length in Prefix.objects.filter(
                namespace__name__in=namespaces
            ).values_list("network", "prefix_length"):
                existing = ipaddress.ip_network(
                    "%s/%s" % (network, prefix_length), strict=False
                )
                if existing.version == seed_net.version and seed_net.overlaps(existing):
                    self._fail(
                        "Supernet %s for %s overlaps existing prefix %s in a "
                        "namespace this design deploys into"
                        % (seed_net, seed, existing)
                    )


class ${class_name}(DesignJob):
    """${job_name}"""

    site_code = StringVar(
        description="Short site code embedded in device/rack names",
        regex=r"^[A-Za-z0-9]{2,12}$$",
    )
    site_name = StringVar(
        description="Name of the new site location",
        # Quote/Jinja-safe: this value lands inside the rendered design text.
        regex=r"^[^'\\"{}%]{1,100}$$",
    )
    parent_location = ObjectVar(
        model=Location, description="Existing parent for the new site"
    )
${supernet_vars}
    class Meta:
        name = "${job_name}"
        description = "${job_description}"
        version = "${template_version}"
        design_files = ${design_files}
        context_class = ${class_name}Context
${extensions_line}        has_sensitive_variables = False
        is_singleton = True
        # A full-site run outlives Nautobot's default Celery limits
        # (300s soft / 600s hard SIGKILL).
        soft_time_limit = ${soft_time_limit}
        time_limit = ${time_limit}
'''
)


def _class_name(template_id: str) -> str:
    return "".join(part.capitalize() for part in template_id.replace("-", "_").split("_"))


def _collision_name_templates(spec: SiteSpec, pmap: ParamMap) -> dict[str, list[str]]:
    """Rendered names that are pure site_code substitutions -> Python format
    strings for the generated collision validator. Names carrying any other
    Jinja (escapes, complex expressions) are skipped — the validator only
    checks what it can compute."""
    out: dict[str, list[str]] = {}
    for family in ("devices", "racks", "rack_groups"):
        names = []
        for obj in spec.entries(family):
            rendered = apply_name_patterns(obj["name"], pmap.name_patterns)
            if isinstance(rendered, Placeholder):
                as_format = str(rendered).replace("{{ site_code }}", "\x00")
                if "{" not in as_format and "}" not in as_format:
                    names.append(as_format.replace("\x00", "{site_code}"))
        if names:
            out[family] = sorted(set(names))
    vlan_group = pmap.vlan_group_name.replace("{{ site_code }}", "\x00")
    if "{" not in vlan_group and "}" not in vlan_group and spec.entries("vlans"):
        out["vlan_groups"] = [vlan_group.replace("\x00", "{site_code}")]
    return out


def render_job_module(
    spec: SiteSpec, pmap: ParamMap, design_files: list[str], has_cabling: bool
) -> str:
    object_count = sum(len(spec.entries(key)) for key in spec.objects)
    soft_limit = max(900, object_count * 5)

    supernet_vars = "".join(
        "    {seed} = IPNetworkVar(description=\"Replaces source supernet {source}\")\n".format(
            seed=entry["seed"], source=entry["source"]
        )
        for entry in pmap.supernets
    )

    parent_lt = (spec.meta.get("source") or {}).get("parent_location_type") or ""

    substitutions = {
        "template_id": pmap.template_id,
        "source_site_code": pmap.source_site_code,
        "references_json": json.dumps(spec.references, indent=2, sort_keys=True),
        "class_name": _class_name(pmap.template_id),
        "job_name": f"Deploy site from template: {pmap.template_id}",
        "job_description": (
            f"Generated from golden site {pmap.source_site_code}; "
            "review the package README before running."
        ),
        "template_version": str(spec.meta.get("template_version", "0")),
        "supernet_vars": supernet_vars,
        "soft_time_limit": soft_limit,
        "time_limit": soft_limit * 2,
        "supernet_seeds": repr({e["seed"]: e["source"] for e in pmap.supernets}),
        "parent_location_type": repr(parent_lt),
        "created_name_templates": repr(_collision_name_templates(spec, pmap)),
        "design_files": repr(design_files),
        "extension_import": (
            "from nautobot_design_builder.contrib.ext import CableConnectionExtension"
            if has_cabling
            else ""
        ),
        "extensions_line": (
            "        extensions = [CableConnectionExtension]\n" if has_cabling else ""
        ),
    }
    # safe_substitute: captured literals inside references_json may contain
    # stray '$' characters that must not be treated as placeholders.
    return _MODULE_TEMPLATE.safe_substitute(substitutions)
