"""Assemble the full design package directory.

Layout (standard Design Builder jobs-in-git, demo-designs style):

    <out>/jobs/__init__.py                 register_jobs(...)
    <out>/jobs/<slug>/__init__.py          generated Context + DesignJob
    <out>/jobs/<slug>/designs/000N_*.yaml.j2
    <out>/jobs/<slug>/README.md            review aid: contents, lint, caveats

Output is deterministic for a given (spec, param map): no timestamps, stable
ordering — regenerations produce meaningful git diffs.
"""

from __future__ import annotations

import re
from pathlib import Path

from .. import lint as lint_mod
from ..params import ParamMap
from ..spec import SiteSpec
from .design import render_design_documents
from .job import _class_name, render_job_module


def _slugify(template_id: str) -> str:
    slug = re.sub(r"[^a-z0-9_]+", "_", template_id.lower()).strip("_")
    if not slug or slug[0].isdigit():
        slug = f"design_{slug}"
    return slug


def _readme(spec: SiteSpec, pmap: ParamMap, design_files: list[str]) -> str:
    counts = {
        key: len(spec.entries(key)) for key in spec.objects if spec.entries(key)
    }
    findings = lint_mod.from_dicts(spec.meta.get("lint", []))

    lines = [
        f"# Design package: {pmap.template_id}",
        "",
        "Generated by nautobot-design-template-factory — **do not edit by hand**;",
        "re-run `dtf render` against the spec and parameter map instead.",
        "",
        f"- Source golden site: `{pmap.source_site_code}`",
        f"- Spec schema: `{spec.meta.get('spec_schema')}`,"
        f" captured from Nautobot `{(spec.meta.get('source') or {}).get('nautobot', '?')}`",
        f"- Scope tier: `{spec.meta.get('scope_tier')}`",
        f"- Design files: {', '.join(f'`{f}`' for f in design_files)}",
        "",
        "## Contents",
        "",
    ]
    lines += [f"- {key}: {count}" for key, count in counts.items()]
    lines += [
        "",
        "## Before deploying",
        "",
        "1. Create the `provisioned_from` text custom field, assigned to every",
        "   content type this design creates (locations, racks, devices,",
        "   interfaces, prefixes, VLANs, IPs, cables). The pre-flight validator",
        "   refuses to run without it.",
        "2. Load this repo as a Nautobot Git repository data source providing",
        "   *jobs*, then enable the generated job.",
        "3. First runs go to a scratch/quarantine parent location. Dry-run",
        "   first: the rendered design is attached to the JobResult.",
        "4. Re-running after a partial failure is safe (single transaction,",
        "   full rollback), but re-running against an already-deployed site",
        "   errors on racked devices (upstream issue #207) — this is expected.",
        "",
        "## Operational notes",
        "",
        "- Deploying a full site fires webhooks/JobHooks per created object —",
        "  clear the burst with downstream system owners before the first",
        "  production run.",
        "- Run this job on a dedicated queue if your default workers also serve",
        "  interactive jobs (a full-site run holds a transaction for minutes).",
        "- Restrict who may run this job via Nautobot object permissions — it is",
        "  object-creation-as-a-service.",
        "- Created objects are stamped via the `provisioned_from` custom field.",
        "  Exceptions in v1: cables and IP-to-interface assignment rows are NOT",
        "  stamped (no supported path for custom fields through connect_cable).",
        "- This package targets Design Builder >=3.1 on Nautobot 3.x.",
        "",
        "## Inferred Design Builder compositions (spike gate 2)",
        "",
        "These patterns are architecturally sound but not doc-exampled upstream;",
        "they are validated by the Phase A spike before production use:",
        "",
        "- parent lookup by pk dict form for the site root location",
        "- second-pass `!update` on devices to set primary IPs",
        "- `!update:name` on template-born components nested under a device",
        "- `ip_address_to_interfaces` as the through-model design key",
        "- namespace pinning via explicit parent prefix refs",
        "- connect_cable payloads carrying type/label and cross-family endpoints",
        "",
        "## Capture lint findings (what this template knowingly omits)",
        "",
        lint_mod.render_markdown(findings, title="").strip() or "None recorded.",
        "",
    ]
    return "\n".join(lines) + "\n"


def render_package(spec: SiteSpec, pmap: ParamMap, out_dir: str | Path) -> list[Path]:
    out = Path(out_dir)
    slug = _slugify(pmap.template_id)
    package_dir = out / "jobs" / slug
    designs_dir = package_dir / "designs"
    designs_dir.mkdir(parents=True, exist_ok=True)

    documents = render_design_documents(spec, pmap)
    # Meta.design_files resolve relative to the job class's module directory;
    # the files are written under <package>/designs/, so the 'designs/...'
    # prefix must be preserved.
    design_files = [name for name, _ in documents]
    has_cabling = any("cabling" in name for name, _ in documents)

    written: list[Path] = []

    for name, text in documents:
        path = package_dir / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        written.append(path)

    job_module = render_job_module(spec, pmap, design_files, has_cabling)
    job_path = package_dir / "__init__.py"
    job_path.write_text(job_module, encoding="utf-8")
    written.append(job_path)

    class_name = _class_name(pmap.template_id)
    jobs_init = out / "jobs" / "__init__.py"
    jobs_init.write_text(
        '"""Generated by nautobot-design-template-factory — DO NOT EDIT."""\n\n'
        f"from nautobot.apps.jobs import register_jobs\n\n"
        f"from .{slug} import {class_name}\n\n"
        f"register_jobs({class_name})\n",
        encoding="utf-8",
    )
    written.append(jobs_init)

    readme_path = package_dir / "README.md"
    readme_path.write_text(_readme(spec, pmap, design_files), encoding="utf-8")
    written.append(readme_path)

    return written
